In [24]:
import re
import time

In [1]:
txt = '''450
00:17:53,457 --> 00:17:56,175
Okay, but, um,
thanks for being with us.

451
00:17:56,175 --> 00:17:58,616
But, um, if there's any
college kids watching,

452
00:17:58,616 --> 00:18:01,610
But, um, but, um, but, um,
but, um, but, um,

453
00:18:01,610 --> 00:18:03,656
We have to drink, professor.

454
00:18:03,656 --> 00:18:07,507
It's the rules.
She said "But, um"

455
00:18:09,788 --> 00:18:12,515
But, um, but, um, but, um...
god help us all.
'''

In [5]:
len(re.findall('But, um', txt))

4

In [6]:
re.search('But, um', txt).count()

AttributeError: '_sre.SRE_Match' object has no attribute 'count'

In [7]:
len(re.findall('[B,b]ut, um', txt))

11

In [8]:
(re.search('[B,b]ut, um', txt)).count()

AttributeError: '_sre.SRE_Match' object has no attribute 'count'

In [9]:
str = """Email_Address,Nickname,Group_Status,Join_Year
aa@aaa.com,aa,Owner,2014
bb@bbb.com,bb,Member,2015
cc@ccc.com,cc,Member,2017
dd@ddd.com,dd,Member,2016
ee@eee.com,ee,Member,2020
"""

In [13]:
for i in re.finditer('([a-zA-Z]+)@([a-zA-Z]+).(com)', str):
    print(i.group(2))

aaa
bbb
ccc
ddd
eee


In [21]:
a = [1,2,3,4,5] 
b = [6,7,8,9]
a.extend(b)
a

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [22]:
date_format = "%d/%m/%Y"

In [29]:
import numpy as np

In [31]:
np.identity(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [32]:
train_set = np.array([1, 2, 3])
test_set = np.array([[0, 1, 2], [1, 2, 3]])

In [35]:
resulting_set = np.vstack([train_set, test_set])

In [36]:
resulting_set

array([[1, 2, 3],
       [0, 1, 2],
       [1, 2, 3]])

In [37]:
import pandas as pd
train  = pd.DataFrame({'id':[1,2,4],'features':[["A","B","C"],["A","D","E"],["C","D","F"]]})

In [38]:
train['features_t'] = train["features"].apply(lambda x: " ".join(["_".join(i.split(" ")) for i in x]))

In [40]:
train['features_t']

0    A B C
1    A D E
2    C D F
Name: features_t, dtype: object

In [41]:
def fun(x):
    x[0] = 5
    return x

In [42]:
g = [10,11,12]

In [43]:
print(fun(g),g)

[5, 11, 12] [5, 11, 12]


In [44]:
df = pd.DataFrame({'Click_Id':['A','B','C','D','E'],'Count':[100,200,300,400,250]})

In [45]:
df.rename(columns = {'Count':'Click_Count'})

Click_Id  Click_Count
0        A          100
1        B          200
2        C          300
3        D          400
4        E          250

In [47]:
df.columns

Index(['Click_Id', 'Count'], dtype='object')

In [48]:
df1 = df

In [49]:
df.loc[df.Click_Id == 'A', 'Count'] += 100

In [50]:
df.Count.values,df1.Count.values

(array([200, 200, 300, 400, 250], dtype=int64),
 array([200, 200, 300, 400, 250], dtype=int64))

In [51]:
D = ['A','B','C','D','E','AA','AB']

In [52]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [53]:
le.fit_transform(D)

array([0, 3, 4, 5, 6, 1, 2], dtype=int64)

In [54]:
df = pd.DataFrame({'Id':[1,2,3,4],'val':[2,5,np.nan,6]})

In [55]:
df.val == np.nan

0    False
1    False
2    False
3    False
Name: val, dtype: bool

In [56]:
np.square(2)

4

In [1]:
len

<function len>